apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
  namespace: {{ default "default" .Values.namespace }}
  labels: {{ include "labels.standard" . | indent 4 }}
data:
  {{- range $key, $value := .Values.envSecrets }}
  {{ template "app.envkey" $key }}: "{{ $value | b64enc }}"
  {{- end }}
{{- if .Values.tls.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-tls
  namespace: {{ default "default" .Values.namespace }}
  labels: {{ include "labels.standard" . | indent 4 }}
type: kubernetes.io/tls
data:
    tls.crt: {{ .Values.tls.certificate | b64enc }}
    tls.key: {{ .Values.tls.key | b64enc }}
{{- end }}
