{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app.serviceAccountName" . }}
  namespace: {{ default "default" .Values.namespace }}
  labels: {{ include "labels.standard" . | indent 4 }}
{{- end }}
