version: "3.9"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "3000:3000"

volumes:
  postgres-data:
